# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Updates match certificates"
  lane :update_match do
    if is_ci
      setup_ci
      api_key = app_store_connect_api_key(
        "key_id": ENV['APPLE_APP_STORE_API_KEY_ID'],
        "issuer_id": ENV['APPLE_APPSTORE_API_ISSUER_ID'],
        "key_content": ENV['APPLE_APP_STORE_API_KEY']
      )
    end
    if !is_ci
      api_key = app_store_connect_api_key(
        key_id: "OK4PLSIUW9C6",
        key_filepath: "/Users/justinkumpe/Documents/ApiKey_OK4PLSIUW9C6.p8",
    )
    end
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "appstore"
    )
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "development"
    )
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "developer_id"
    )
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "developer_id_installer"
    )
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "mac_installer_distribution"
    )
  end

  lane :matchget do
	if is_ci
		setup_ci
	end
  match(generate_apple_certs: true, type: "development", readonly: is_ci, app_identifier: "com.kumpeapps.flet.kumpe3dkiosk", git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], git_url: "https://github.com/kumpeapps/fastlane_certs.git")
  match(generate_apple_certs: true, type: "appstore", readonly: is_ci, app_identifier: "com.kumpeapps.flet.kumpe3dkiosk", git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], git_url: "https://github.com/kumpeapps/fastlane_certs.git")
  end
end
